# Generated by Django 5.0 on 2026-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uz', "O'zbek")], default='en', max_length=5),
        ),
    ]
