# Generated by Django 5.0 on 2026-05-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_botuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
