# Generated by Django 5.0.14 on 2026-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('channel_username', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('invite_link', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Channel',
                'verbose_name_plural': 'Subscription Channels',
                'ordering': ['title'],
            },
        ),
    ]
