# Generated by Django 5.0 on 2026-05-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
